### PR TITLE
fix: Noise Period value passed to hardware

### LINKED ISSUE #1: Incorrect Noise Period value passed to hardware
src/ayfx.asm Line 312 should be `cp #20`. As it stands `sub #20`, subtracts from the Noise Period value from the accumulator to perform the end-of-effect test, but the original value is not restored before storing in Line 322 `ld (afxNseMix+1),a` which is later used as the value to write directly into the AY-3 Noise Period register.

The fix to Line 312 requires that Line 313 be changed to `jr nz,afxFrame2`

This is a bug in the original code.

### PR DESCRIPTION
**Pull request by remy**
Fixes #1

### CODE REVIEW

**Review by howprice — CHANGES_REQUESTED** [review]
I think the `sub` on line 312 should be a `cp`, otherwise the noise period value is corrupted.

**Comment by remy** [comment]
Okay, I've tweaked that too. I'm not very experienced with asm - I can read these changes but I don't know how they all fit into the larger picture (though I wrote all the driver support, it's massively simpler).

Looks good now?

**Review by howprice — APPROVED** [review]
Great. I integrated the original code into my game and spotted this while stepping through with the debugger.

**Comment by remy** [comment]
cheers for the help - I'll also update the published drv.

**Pull request merged**
